version: '3'
services:
  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongodb
      - kafka
  consumer-1:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - kafka
  consumer-2:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - kafka
  consumer-3:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - kafka
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "my-topic:1:1" 
    depends_on:
      - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    environment:
      KAFKA_ADVERTISED_HOST_NAME: zookeeper
      KAFKA_ADVERTISED_PORT: 2181

volumes:
  mongodb-data:
